// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: rtrs_quality.proto

package guard_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// RTRS请求包定义
type QualityReqBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalInfo *QualityReqBody_GlobalInfo   `protobuf:"bytes,1,opt,name=global_info,json=globalInfo,proto3" json:"global_info,omitempty"`   // 请求级全局信息
	ReqPosInfo []*QualityReqBody_ReqPosInfo `protobuf:"bytes,2,rep,name=req_pos_info,json=reqPosInfo,proto3" json:"req_pos_info,omitempty"` // 排序位置, 一次请求可包含多个位置
}

func (x *QualityReqBody) Reset() {
	*x = QualityReqBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtrs_quality_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualityReqBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityReqBody) ProtoMessage() {}

func (x *QualityReqBody) ProtoReflect() protoreflect.Message {
	mi := &file_rtrs_quality_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityReqBody.ProtoReflect.Descriptor instead.
func (*QualityReqBody) Descriptor() ([]byte, []int) {
	return file_rtrs_quality_proto_rawDescGZIP(), []int{0}
}

func (x *QualityReqBody) GetGlobalInfo() *QualityReqBody_GlobalInfo {
	if x != nil {
		return x.GlobalInfo
	}
	return nil
}

func (x *QualityReqBody) GetReqPosInfo() []*QualityReqBody_ReqPosInfo {
	if x != nil {
		return x.ReqPosInfo
	}
	return nil
}

// RTRS回复包定义
type QualityRspBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 推荐位返回结果
	RspPosInfo []*QualityRspBody_RspPosInfo `protobuf:"bytes,1,rep,name=rsp_pos_info,json=rspPosInfo,proto3" json:"rsp_pos_info,omitempty"`
}

func (x *QualityRspBody) Reset() {
	*x = QualityRspBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtrs_quality_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualityRspBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityRspBody) ProtoMessage() {}

func (x *QualityRspBody) ProtoReflect() protoreflect.Message {
	mi := &file_rtrs_quality_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityRspBody.ProtoReflect.Descriptor instead.
func (*QualityRspBody) Descriptor() ([]byte, []int) {
	return file_rtrs_quality_proto_rawDescGZIP(), []int{1}
}

func (x *QualityRspBody) GetRspPosInfo() []*QualityRspBody_RspPosInfo {
	if x != nil {
		return x.RspPosInfo
	}
	return nil
}

// 请求位置信息
type QualityReqBody_ReqPosInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PosId         uint32         `protobuf:"varint,1,opt,name=pos_id,json=posId,proto3" json:"pos_id,omitempty"`                          // 推荐位置定义 与scene含义相同
	MixReq        *Request       `protobuf:"bytes,2,opt,name=mix_req,json=mixReq,proto3" json:"mix_req,omitempty"`                        // 保存从guard发送过来的包体，仅scheduler so理解，下游rtrs so不用该成员
	PosDetailInfo *RecommendInfo `protobuf:"bytes,3,opt,name=pos_detail_info,json=posDetailInfo,proto3" json:"pos_detail_info,omitempty"` //描述该场景的具体信息，schedule so传递信息给下游rtrs so
	AbtestReq     *AbtestReq     `protobuf:"bytes,4,opt,name=abtest_req,json=abtestReq,proto3" json:"abtest_req,omitempty"`               //仅在访问abtest时使用，abtest请求包信息
}

func (x *QualityReqBody_ReqPosInfo) Reset() {
	*x = QualityReqBody_ReqPosInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtrs_quality_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualityReqBody_ReqPosInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityReqBody_ReqPosInfo) ProtoMessage() {}

func (x *QualityReqBody_ReqPosInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rtrs_quality_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityReqBody_ReqPosInfo.ProtoReflect.Descriptor instead.
func (*QualityReqBody_ReqPosInfo) Descriptor() ([]byte, []int) {
	return file_rtrs_quality_proto_rawDescGZIP(), []int{0, 0}
}

func (x *QualityReqBody_ReqPosInfo) GetPosId() uint32 {
	if x != nil {
		return x.PosId
	}
	return 0
}

func (x *QualityReqBody_ReqPosInfo) GetMixReq() *Request {
	if x != nil {
		return x.MixReq
	}
	return nil
}

func (x *QualityReqBody_ReqPosInfo) GetPosDetailInfo() *RecommendInfo {
	if x != nil {
		return x.PosDetailInfo
	}
	return nil
}

func (x *QualityReqBody_ReqPosInfo) GetAbtestReq() *AbtestReq {
	if x != nil {
		return x.AbtestReq
	}
	return nil
}

type QualityReqBody_GlobalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogId             []byte             `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`                                         // 用于唯一确定某次请求
	RuleAppDirectInfo *RuleAppDirectInfo `protobuf:"bytes,2,opt,name=rule_app_direct_info,json=ruleAppDirectInfo,proto3" json:"rule_app_direct_info,omitempty"` //每个app的定向条件
	//设备相关信息
	RecomDevice *DeviceInfo `protobuf:"bytes,3,opt,name=recom_device,json=recomDevice,proto3" json:"recom_device,omitempty"`
	//位置相关信息
	RecomLocation *LocationInfo `protobuf:"bytes,4,opt,name=recom_location,json=recomLocation,proto3" json:"recom_location,omitempty"`
	//网络相关信息
	RecomNetwork *NetworkInfo `protobuf:"bytes,5,opt,name=recom_network,json=recomNetwork,proto3" json:"recom_network,omitempty"`
}

func (x *QualityReqBody_GlobalInfo) Reset() {
	*x = QualityReqBody_GlobalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtrs_quality_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualityReqBody_GlobalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityReqBody_GlobalInfo) ProtoMessage() {}

func (x *QualityReqBody_GlobalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rtrs_quality_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityReqBody_GlobalInfo.ProtoReflect.Descriptor instead.
func (*QualityReqBody_GlobalInfo) Descriptor() ([]byte, []int) {
	return file_rtrs_quality_proto_rawDescGZIP(), []int{0, 1}
}

func (x *QualityReqBody_GlobalInfo) GetLogId() []byte {
	if x != nil {
		return x.LogId
	}
	return nil
}

func (x *QualityReqBody_GlobalInfo) GetRuleAppDirectInfo() *RuleAppDirectInfo {
	if x != nil {
		return x.RuleAppDirectInfo
	}
	return nil
}

func (x *QualityReqBody_GlobalInfo) GetRecomDevice() *DeviceInfo {
	if x != nil {
		return x.RecomDevice
	}
	return nil
}

func (x *QualityReqBody_GlobalInfo) GetRecomLocation() *LocationInfo {
	if x != nil {
		return x.RecomLocation
	}
	return nil
}

func (x *QualityReqBody_GlobalInfo) GetRecomNetwork() *NetworkInfo {
	if x != nil {
		return x.RecomNetwork
	}
	return nil
}

type QualityRspBody_RspPosInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MixRsp        *Response      `protobuf:"bytes,1,opt,name=mix_rsp,json=mixRsp,proto3" json:"mix_rsp,omitempty"`                        //仅schedule so使用，保存schedule返回给guard的回包
	PosDetailInfo *RecommendInfo `protobuf:"bytes,2,opt,name=pos_detail_info,json=posDetailInfo,proto3" json:"pos_detail_info,omitempty"` //描述该场景的具体信息
	AbtestRsp     *AbtestRsp     `protobuf:"bytes,3,opt,name=abtest_rsp,json=abtestRsp,proto3" json:"abtest_rsp,omitempty"`               //仅在访问abtest时使用，abtest回包信息
	RtrsCode      int32          `protobuf:"varint,1000,opt,name=rtrs_code,json=rtrsCode,proto3" json:"rtrs_code,omitempty"`
}

func (x *QualityRspBody_RspPosInfo) Reset() {
	*x = QualityRspBody_RspPosInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtrs_quality_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QualityRspBody_RspPosInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QualityRspBody_RspPosInfo) ProtoMessage() {}

func (x *QualityRspBody_RspPosInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rtrs_quality_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QualityRspBody_RspPosInfo.ProtoReflect.Descriptor instead.
func (*QualityRspBody_RspPosInfo) Descriptor() ([]byte, []int) {
	return file_rtrs_quality_proto_rawDescGZIP(), []int{1, 0}
}

func (x *QualityRspBody_RspPosInfo) GetMixRsp() *Response {
	if x != nil {
		return x.MixRsp
	}
	return nil
}

func (x *QualityRspBody_RspPosInfo) GetPosDetailInfo() *RecommendInfo {
	if x != nil {
		return x.PosDetailInfo
	}
	return nil
}

func (x *QualityRspBody_RspPosInfo) GetAbtestRsp() *AbtestRsp {
	if x != nil {
		return x.AbtestRsp
	}
	return nil
}

func (x *QualityRspBody_RspPosInfo) GetRtrsCode() int32 {
	if x != nil {
		return x.RtrsCode
	}
	return 0
}

var File_rtrs_quality_proto protoreflect.FileDescriptor

var file_rtrs_quality_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x74, 0x72, 0x73, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x1a, 0x0f,
	0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x13, 0x72, 0x74, 0x72, 0x73, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x72, 0x74, 0x72, 0x73, 0x5f, 0x61, 0x62, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x05, 0x0a, 0x0e, 0x51, 0x75, 0x61, 0x6c,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x44, 0x0a, 0x0b, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x45, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x6f, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70,
	0x62, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x42, 0x6f, 0x64, 0x79,
	0x2e, 0x52, 0x65, 0x71, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x72, 0x65, 0x71,
	0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xcd, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x50,
	0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x73, 0x49, 0x64, 0x12, 0x33, 0x0a,
	0x07, 0x6d, 0x69, 0x78, 0x5f, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x6d, 0x69, 0x78, 0x52,
	0x65, 0x71, 0x12, 0x3f, 0x0a, 0x0f, 0x70, 0x6f, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x70, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x0a, 0x61, 0x62, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x65,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f,
	0x70, 0x62, 0x2e, 0x41, 0x62, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x52, 0x09, 0x61, 0x62,
	0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0xa5, 0x02, 0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x4c, 0x0a,
	0x14, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x75,
	0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x72, 0x75, 0x6c, 0x65, 0x41, 0x70,
	0x70, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x5f, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x5f, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x22,
	0xaf, 0x02, 0x0a, 0x0e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x73, 0x70, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x45, 0x0a, 0x0c, 0x72, 0x73, 0x70, 0x5f, 0x70, 0x6f, 0x73, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64,
	0x5f, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x73, 0x70, 0x42, 0x6f,
	0x64, 0x79, 0x2e, 0x52, 0x73, 0x70, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x72,
	0x73, 0x70, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xd5, 0x01, 0x0a, 0x0a, 0x52, 0x73,
	0x70, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x34, 0x0a, 0x07, 0x6d, 0x69, 0x78, 0x5f,
	0x72, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x5f, 0x70, 0x62, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x6d, 0x69, 0x78, 0x52, 0x73, 0x70, 0x12, 0x3f,
	0x0a, 0x0f, 0x70, 0x6f, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0d, 0x70, 0x6f, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x32, 0x0a, 0x0a, 0x61, 0x62, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x72, 0x73, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x70, 0x62, 0x2e, 0x41,
	0x62, 0x74, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x52, 0x09, 0x61, 0x62, 0x74, 0x65, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x74, 0x72, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x74, 0x72, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtrs_quality_proto_rawDescOnce sync.Once
	file_rtrs_quality_proto_rawDescData = file_rtrs_quality_proto_rawDesc
)

func file_rtrs_quality_proto_rawDescGZIP() []byte {
	file_rtrs_quality_proto_rawDescOnce.Do(func() {
		file_rtrs_quality_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtrs_quality_proto_rawDescData)
	})
	return file_rtrs_quality_proto_rawDescData
}

var file_rtrs_quality_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rtrs_quality_proto_goTypes = []interface{}{
	(*QualityReqBody)(nil),            // 0: guard_pb.QualityReqBody
	(*QualityRspBody)(nil),            // 1: guard_pb.QualityRspBody
	(*QualityReqBody_ReqPosInfo)(nil), // 2: guard_pb.QualityReqBody.ReqPosInfo
	(*QualityReqBody_GlobalInfo)(nil), // 3: guard_pb.QualityReqBody.GlobalInfo
	(*QualityRspBody_RspPosInfo)(nil), // 4: guard_pb.QualityRspBody.RspPosInfo
	(*Request)(nil),                   // 5: guard_pb.schedule.Request
	(*RecommendInfo)(nil),             // 6: guard_pb.RecommendInfo
	(*AbtestReq)(nil),                 // 7: guard_pb.AbtestReq
	(*RuleAppDirectInfo)(nil),         // 8: guard_pb.RuleAppDirectInfo
	(*DeviceInfo)(nil),                // 9: guard_pb.DeviceInfo
	(*LocationInfo)(nil),              // 10: guard_pb.LocationInfo
	(*NetworkInfo)(nil),               // 11: guard_pb.NetworkInfo
	(*Response)(nil),                  // 12: guard_pb.schedule.Response
	(*AbtestRsp)(nil),                 // 13: guard_pb.AbtestRsp
}
var file_rtrs_quality_proto_depIdxs = []int32{
	3,  // 0: guard_pb.QualityReqBody.global_info:type_name -> guard_pb.QualityReqBody.GlobalInfo
	2,  // 1: guard_pb.QualityReqBody.req_pos_info:type_name -> guard_pb.QualityReqBody.ReqPosInfo
	4,  // 2: guard_pb.QualityRspBody.rsp_pos_info:type_name -> guard_pb.QualityRspBody.RspPosInfo
	5,  // 3: guard_pb.QualityReqBody.ReqPosInfo.mix_req:type_name -> guard_pb.schedule.Request
	6,  // 4: guard_pb.QualityReqBody.ReqPosInfo.pos_detail_info:type_name -> guard_pb.RecommendInfo
	7,  // 5: guard_pb.QualityReqBody.ReqPosInfo.abtest_req:type_name -> guard_pb.AbtestReq
	8,  // 6: guard_pb.QualityReqBody.GlobalInfo.rule_app_direct_info:type_name -> guard_pb.RuleAppDirectInfo
	9,  // 7: guard_pb.QualityReqBody.GlobalInfo.recom_device:type_name -> guard_pb.DeviceInfo
	10, // 8: guard_pb.QualityReqBody.GlobalInfo.recom_location:type_name -> guard_pb.LocationInfo
	11, // 9: guard_pb.QualityReqBody.GlobalInfo.recom_network:type_name -> guard_pb.NetworkInfo
	12, // 10: guard_pb.QualityRspBody.RspPosInfo.mix_rsp:type_name -> guard_pb.schedule.Response
	6,  // 11: guard_pb.QualityRspBody.RspPosInfo.pos_detail_info:type_name -> guard_pb.RecommendInfo
	13, // 12: guard_pb.QualityRspBody.RspPosInfo.abtest_rsp:type_name -> guard_pb.AbtestRsp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_rtrs_quality_proto_init() }
func file_rtrs_quality_proto_init() {
	if File_rtrs_quality_proto != nil {
		return
	}
	file_recommend_proto_init()
	file_rtrs_schedule_proto_init()
	file_rtrs_abtest_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rtrs_quality_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualityReqBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtrs_quality_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualityRspBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtrs_quality_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualityReqBody_ReqPosInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtrs_quality_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualityReqBody_GlobalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtrs_quality_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QualityRspBody_RspPosInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtrs_quality_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtrs_quality_proto_goTypes,
		DependencyIndexes: file_rtrs_quality_proto_depIdxs,
		MessageInfos:      file_rtrs_quality_proto_msgTypes,
	}.Build()
	File_rtrs_quality_proto = out.File
	file_rtrs_quality_proto_rawDesc = nil
	file_rtrs_quality_proto_goTypes = nil
	file_rtrs_quality_proto_depIdxs = nil
}
