// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed_proto/mobil_user_model.proto

package feed_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionExpoItem struct {
	Item                 string   `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Ts                   uint64   `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Dur                  float64  `protobuf:"fixed64,7,opt,name=dur,proto3" json:"dur,omitempty"`
	PlayType             uint32   `protobuf:"varint,9,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionExpoItem) Reset()         { *m = ActionExpoItem{} }
func (m *ActionExpoItem) String() string { return proto.CompactTextString(m) }
func (*ActionExpoItem) ProtoMessage()    {}
func (*ActionExpoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_274800b7f896bd11, []int{0}
}

func (m *ActionExpoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionExpoItem.Unmarshal(m, b)
}
func (m *ActionExpoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionExpoItem.Marshal(b, m, deterministic)
}
func (m *ActionExpoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionExpoItem.Merge(m, src)
}
func (m *ActionExpoItem) XXX_Size() int {
	return xxx_messageInfo_ActionExpoItem.Size(m)
}
func (m *ActionExpoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionExpoItem.DiscardUnknown(m)
}

var xxx_messageInfo_ActionExpoItem proto.InternalMessageInfo

func (m *ActionExpoItem) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

func (m *ActionExpoItem) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *ActionExpoItem) GetDur() float64 {
	if m != nil {
		return m.Dur
	}
	return 0
}

func (m *ActionExpoItem) GetPlayType() uint32 {
	if m != nil {
		return m.PlayType
	}
	return 0
}

//  端侧用户模型
type MobilUserModel struct {
	ExposeList           []*ActionExpoItem `protobuf:"bytes,4,rep,name=expose_list,json=exposeList,proto3" json:"expose_list,omitempty"`
	ClickList            []*ActionExpoItem `protobuf:"bytes,13,rep,name=click_list,json=clickList,proto3" json:"click_list,omitempty"`
	LikeList             []*ActionExpoItem `protobuf:"bytes,9,rep,name=like_list,json=likeList,proto3" json:"like_list,omitempty"`
	Di                   []*ActionExpoItem `protobuf:"bytes,10,rep,name=di,proto3" json:"di,omitempty"`
	ShareList            []*ActionExpoItem `protobuf:"bytes,11,rep,name=share_list,json=shareList,proto3" json:"share_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MobilUserModel) Reset()         { *m = MobilUserModel{} }
func (m *MobilUserModel) String() string { return proto.CompactTextString(m) }
func (*MobilUserModel) ProtoMessage()    {}
func (*MobilUserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_274800b7f896bd11, []int{1}
}

func (m *MobilUserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobilUserModel.Unmarshal(m, b)
}
func (m *MobilUserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobilUserModel.Marshal(b, m, deterministic)
}
func (m *MobilUserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobilUserModel.Merge(m, src)
}
func (m *MobilUserModel) XXX_Size() int {
	return xxx_messageInfo_MobilUserModel.Size(m)
}
func (m *MobilUserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MobilUserModel.DiscardUnknown(m)
}

var xxx_messageInfo_MobilUserModel proto.InternalMessageInfo

func (m *MobilUserModel) GetExposeList() []*ActionExpoItem {
	if m != nil {
		return m.ExposeList
	}
	return nil
}

func (m *MobilUserModel) GetClickList() []*ActionExpoItem {
	if m != nil {
		return m.ClickList
	}
	return nil
}

func (m *MobilUserModel) GetLikeList() []*ActionExpoItem {
	if m != nil {
		return m.LikeList
	}
	return nil
}

func (m *MobilUserModel) GetDi() []*ActionExpoItem {
	if m != nil {
		return m.Di
	}
	return nil
}

func (m *MobilUserModel) GetShareList() []*ActionExpoItem {
	if m != nil {
		return m.ShareList
	}
	return nil
}

func init() {
	proto.RegisterType((*ActionExpoItem)(nil), "feed.api.ActionExpoItem")
	proto.RegisterType((*MobilUserModel)(nil), "feed.api.MobilUserModel")
}

func init() { proto.RegisterFile("feed_proto/mobil_user_model.proto", fileDescriptor_274800b7f896bd11) }

var fileDescriptor_274800b7f896bd11 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0x69, 0xb7, 0xac, 0xcd, 0x94, 0x2d, 0x92, 0x53, 0xc0, 0x4b, 0xdd, 0x53, 0x4e, 0x15,
	0x14, 0x11, 0x8f, 0x0a, 0x1e, 0x04, 0xf7, 0x52, 0xf4, 0xe2, 0xa5, 0x74, 0xdb, 0x11, 0x87, 0x4d,
	0x4d, 0x48, 0xb2, 0xb0, 0xfd, 0x19, 0xbf, 0x55, 0x92, 0x5d, 0x05, 0x4f, 0xbd, 0x0d, 0xc3, 0x7b,
	0xcc, 0x83, 0x81, 0xcb, 0x0f, 0xc4, 0xa1, 0x35, 0x56, 0x7b, 0x7d, 0x35, 0xea, 0x2d, 0xa9, 0x76,
	0xef, 0xd0, 0xb6, 0xa3, 0x1e, 0x50, 0xd5, 0x71, 0xcd, 0xf3, 0x80, 0xd4, 0x9d, 0xa1, 0x75, 0x0f,
	0xe5, 0x43, 0xef, 0x49, 0x7f, 0x3d, 0x1d, 0x8c, 0x7e, 0xf6, 0x38, 0x72, 0x0e, 0x19, 0x79, 0x1c,
	0x45, 0x56, 0x25, 0x92, 0x35, 0x71, 0xe6, 0x25, 0xa4, 0xde, 0x89, 0x65, 0x95, 0xc8, 0xac, 0x49,
	0xbd, 0xe3, 0xe7, 0xb0, 0x18, 0xf6, 0x56, 0x9c, 0x55, 0x89, 0x4c, 0x9a, 0x30, 0xf2, 0x0b, 0x60,
	0x46, 0x75, 0x53, 0xeb, 0x27, 0x83, 0x82, 0x55, 0x89, 0x5c, 0x35, 0x79, 0x58, 0xbc, 0x4e, 0x06,
	0xd7, 0xdf, 0x29, 0x94, 0x9b, 0x50, 0xf2, 0xe6, 0xd0, 0x6e, 0x42, 0x07, 0xbf, 0x87, 0x02, 0x0f,
	0x46, 0x3b, 0x6c, 0x15, 0x39, 0x2f, 0xb2, 0x6a, 0x21, 0x8b, 0x6b, 0x51, 0xff, 0x76, 0xd5, 0xff,
	0xa3, 0x1a, 0x38, 0xc2, 0x2f, 0xe4, 0x3c, 0xbf, 0x03, 0xe8, 0x15, 0xf5, 0xbb, 0xa3, 0xb9, 0x9a,
	0x31, 0x59, 0x64, 0xa3, 0x78, 0x0b, 0x4c, 0xd1, 0xee, 0x74, 0x91, 0xcd, 0x78, 0x79, 0x40, 0xa3,
	0x26, 0x21, 0x1d, 0x48, 0xc0, 0x0c, 0x9f, 0x0e, 0x14, 0xca, 0xdc, 0x67, 0x67, 0x4f, 0x17, 0x8a,
	0xb9, 0xb2, 0xc8, 0x86, 0x13, 0x8f, 0xf0, 0xfe, 0xf7, 0x91, 0xed, 0x32, 0xbe, 0xe8, 0xe6, 0x27,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x49, 0x2c, 0xde, 0xc7, 0x01, 0x00, 0x00,
}
