// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feed_proto/video_item.proto

package feed_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VideoItem struct {
	Id           string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GmtCreate    uint64   `protobuf:"varint,2,opt,name=gmt_create,json=gmtCreate,proto3" json:"gmt_create,omitempty"`
	GmtModified  uint64   `protobuf:"varint,3,opt,name=gmt_modified,json=gmtModified,proto3" json:"gmt_modified,omitempty"`
	Title        string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ChannelId    string   `protobuf:"bytes,5,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PublishedAt  string   `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ChannelTitle string   `protobuf:"bytes,7,opt,name=channel_title,json=channelTitle,proto3" json:"channel_title,omitempty"`
	CategoryId   string   `protobuf:"bytes,8,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Category     string   `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	VideoUrl     string   `protobuf:"bytes,10,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	Region       string   `protobuf:"bytes,11,opt,name=region,proto3" json:"region,omitempty"`
	Language     string   `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	Duration     uint64   `protobuf:"varint,13,opt,name=duration,proto3" json:"duration,omitempty"`
	CoverImg     string   `protobuf:"bytes,14,opt,name=cover_img,json=coverImg,proto3" json:"cover_img,omitempty"`
	Tags         []string `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	ExpireTime   uint64   `protobuf:"varint,16,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	Status       uint32   `protobuf:"varint,17,opt,name=status,proto3" json:"status,omitempty"`
	//  ~ 199  静态信息保留字段， 以下为统计值字段
	CommentCount         uint64   `protobuf:"varint,200,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	DislikeCount         uint64   `protobuf:"varint,201,opt,name=dislike_count,json=dislikeCount,proto3" json:"dislike_count,omitempty"`
	LikeCount            uint64   `protobuf:"varint,202,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount            uint64   `protobuf:"varint,203,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoItem) Reset()         { *m = VideoItem{} }
func (m *VideoItem) String() string { return proto.CompactTextString(m) }
func (*VideoItem) ProtoMessage()    {}
func (*VideoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e15c2ca049b270ba, []int{0}
}

func (m *VideoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoItem.Unmarshal(m, b)
}
func (m *VideoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoItem.Marshal(b, m, deterministic)
}
func (m *VideoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoItem.Merge(m, src)
}
func (m *VideoItem) XXX_Size() int {
	return xxx_messageInfo_VideoItem.Size(m)
}
func (m *VideoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoItem.DiscardUnknown(m)
}

var xxx_messageInfo_VideoItem proto.InternalMessageInfo

func (m *VideoItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VideoItem) GetGmtCreate() uint64 {
	if m != nil {
		return m.GmtCreate
	}
	return 0
}

func (m *VideoItem) GetGmtModified() uint64 {
	if m != nil {
		return m.GmtModified
	}
	return 0
}

func (m *VideoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoItem) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *VideoItem) GetPublishedAt() string {
	if m != nil {
		return m.PublishedAt
	}
	return ""
}

func (m *VideoItem) GetChannelTitle() string {
	if m != nil {
		return m.ChannelTitle
	}
	return ""
}

func (m *VideoItem) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *VideoItem) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *VideoItem) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *VideoItem) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *VideoItem) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *VideoItem) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *VideoItem) GetCoverImg() string {
	if m != nil {
		return m.CoverImg
	}
	return ""
}

func (m *VideoItem) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *VideoItem) GetExpireTime() uint64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *VideoItem) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *VideoItem) GetCommentCount() uint64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *VideoItem) GetDislikeCount() uint64 {
	if m != nil {
		return m.DislikeCount
	}
	return 0
}

func (m *VideoItem) GetLikeCount() uint64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *VideoItem) GetViewCount() uint64 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func init() {
	proto.RegisterType((*VideoItem)(nil), "feed.api.VideoItem")
}

func init() { proto.RegisterFile("feed_proto/video_item.proto", fileDescriptor_e15c2ca049b270ba) }

var fileDescriptor_e15c2ca049b270ba = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x95, 0x6e, 0xb7, 0x34, 0xd3, 0x76, 0x01, 0x0b, 0x21, 0x8b, 0x15, 0x50, 0xfe, 0x1c,
	0x7a, 0x5a, 0x0e, 0x7c, 0x02, 0xd8, 0x53, 0x0f, 0x5c, 0xaa, 0x85, 0x03, 0x97, 0xc8, 0x1b, 0xcf,
	0xba, 0x23, 0xe2, 0xb8, 0x72, 0x26, 0x05, 0xbe, 0x21, 0x7f, 0xbe, 0x11, 0x27, 0xe4, 0x89, 0x1b,
	0xc1, 0x2d, 0xef, 0xf7, 0xde, 0xbc, 0x71, 0x2c, 0xc3, 0xe5, 0x1d, 0xa2, 0xad, 0x0e, 0x31, 0x70,
	0x78, 0x73, 0x24, 0x8b, 0xa1, 0x22, 0x46, 0x7f, 0x25, 0x40, 0xcd, 0x93, 0x79, 0x65, 0x0e, 0xf4,
	0xf2, 0xcf, 0x14, 0xca, 0x4f, 0xc9, 0xde, 0x32, 0x7a, 0x75, 0x01, 0x13, 0xb2, 0xba, 0x58, 0x17,
	0x9b, 0x72, 0x37, 0x21, 0xab, 0x9e, 0x02, 0x38, 0xcf, 0x55, 0x1d, 0xd1, 0x30, 0xea, 0xc9, 0xba,
	0xd8, 0x4c, 0x77, 0xa5, 0xf3, 0x7c, 0x2d, 0x40, 0xbd, 0x80, 0x65, 0xb2, 0x7d, 0xb0, 0x74, 0x47,
	0x68, 0xf5, 0x99, 0x04, 0x16, 0xce, 0xf3, 0x87, 0x8c, 0xd4, 0x23, 0x38, 0x67, 0xe2, 0x06, 0xf5,
	0x54, 0x4a, 0x07, 0x91, 0x7a, 0xeb, 0xbd, 0x69, 0x5b, 0x6c, 0x2a, 0xb2, 0xfa, 0x5c, 0xac, 0x32,
	0x93, 0xad, 0x4d, 0xbd, 0x87, 0xfe, 0xb6, 0xa1, 0x6e, 0x8f, 0xb6, 0x32, 0xac, 0x67, 0x12, 0x58,
	0x8c, 0xec, 0x1d, 0xab, 0x57, 0xb0, 0x3a, 0x35, 0x0c, 0xfd, 0xf7, 0x24, 0xb3, 0xcc, 0xf0, 0x46,
	0xd6, 0x3c, 0x87, 0x45, 0x6d, 0x18, 0x5d, 0x88, 0xdf, 0xd3, 0x9e, 0xb9, 0x44, 0xe0, 0x84, 0xb6,
	0x56, 0x3d, 0x81, 0xf9, 0x49, 0xe9, 0x52, 0xdc, 0x51, 0xab, 0x4b, 0x28, 0x87, 0x7b, 0xeb, 0x63,
	0xa3, 0x61, 0x30, 0x05, 0x7c, 0x8c, 0x8d, 0x7a, 0x0c, 0xb3, 0x88, 0x8e, 0x42, 0xab, 0x17, 0xe2,
	0x64, 0x95, 0x0a, 0x1b, 0xd3, 0xba, 0xde, 0x38, 0xd4, 0xcb, 0x61, 0xe6, 0xa4, 0x93, 0x67, 0xfb,
	0x68, 0x38, 0x4d, 0xad, 0xe4, 0xa6, 0x46, 0x9d, 0x96, 0xd5, 0xe1, 0x88, 0xb1, 0x22, 0xef, 0xf4,
	0x45, 0x3e, 0x49, 0x02, 0x5b, 0xef, 0x94, 0x82, 0x29, 0x1b, 0xd7, 0xe9, 0xfb, 0xeb, 0xb3, 0x4d,
	0xb9, 0x93, 0xef, 0xf4, 0x6b, 0xf8, 0xed, 0x40, 0x11, 0x2b, 0x26, 0x8f, 0xfa, 0x81, 0xf4, 0xc1,
	0x80, 0x6e, 0xc8, 0x63, 0x3a, 0x61, 0xc7, 0x86, 0xfb, 0x4e, 0x3f, 0x5c, 0x17, 0x9b, 0xd5, 0x2e,
	0x2b, 0xf5, 0x1a, 0x56, 0x75, 0xf0, 0x1e, 0x5b, 0xae, 0xea, 0xd0, 0xb7, 0xac, 0x7f, 0x14, 0x32,
	0xbb, 0xcc, 0xf4, 0x3a, 0xc1, 0x94, 0xb2, 0xd4, 0x35, 0xf4, 0x05, 0x73, 0xea, 0x67, 0x4e, 0x65,
	0x3a, 0xa4, 0x9e, 0x01, 0xfc, 0x13, 0xf9, 0x35, 0x44, 0xca, 0xff, 0xfc, 0x23, 0xe1, 0xd7, 0xec,
	0xff, 0xce, 0x7e, 0x42, 0xe2, 0xbf, 0x87, 0xcf, 0xe3, 0x43, 0xbc, 0x9d, 0xc9, 0xcb, 0x7c, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x37, 0x46, 0x00, 0xb8, 0x02, 0x00, 0x00,
}
