// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: protocol/rank2/tagb.proto

package rank2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpdAlgParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecallType   int32   `protobuf:"varint,1,opt,name=recall_type,json=recallType,proto3" json:"recall_type,omitempty"`        // 按位存储，每一个二进制位表示一个召回通道，命中的话将对应位置1即可
	SoftmaxScore float32 `protobuf:"fixed32,2,opt,name=softmax_score,json=softmaxScore,proto3" json:"softmax_score,omitempty"` // 多分类模型得分
	LitePctr     float32 `protobuf:"fixed32,3,opt,name=lite_pctr,json=litePctr,proto3" json:"lite_pctr,omitempty"`             // 粗排模型ctr得分
	LitePcvr     float32 `protobuf:"fixed32,4,opt,name=lite_pcvr,json=litePcvr,proto3" json:"lite_pcvr,omitempty"`             // 粗排模型cvr得分
	Pctr         float32 `protobuf:"fixed32,5,opt,name=pctr,proto3" json:"pctr,omitempty"`                                     // 模型输出的pctr
	Pcvr         float32 `protobuf:"fixed32,6,opt,name=pcvr,proto3" json:"pcvr,omitempty"`                                     // 模型输出的pcvr
	Pcvr2        float32 `protobuf:"fixed32,7,opt,name=pcvr2,proto3" json:"pcvr2,omitempty"`                                   // 模型输出的pcvr2
	RerankType   int32   `protobuf:"varint,8,opt,name=rerank_type,json=rerankType,proto3" json:"rerank_type,omitempty"`        // 按位存储，每一个二进制位表示一个rerank策略，命中的话将对应位置1即可, 最多支持32种，策略多可以设计成int64支持64种
}

func (x *CpdAlgParam) Reset() {
	*x = CpdAlgParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_rank2_tagb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpdAlgParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpdAlgParam) ProtoMessage() {}

func (x *CpdAlgParam) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_rank2_tagb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpdAlgParam.ProtoReflect.Descriptor instead.
func (*CpdAlgParam) Descriptor() ([]byte, []int) {
	return file_protocol_rank2_tagb_proto_rawDescGZIP(), []int{0}
}

func (x *CpdAlgParam) GetRecallType() int32 {
	if x != nil {
		return x.RecallType
	}
	return 0
}

func (x *CpdAlgParam) GetSoftmaxScore() float32 {
	if x != nil {
		return x.SoftmaxScore
	}
	return 0
}

func (x *CpdAlgParam) GetLitePctr() float32 {
	if x != nil {
		return x.LitePctr
	}
	return 0
}

func (x *CpdAlgParam) GetLitePcvr() float32 {
	if x != nil {
		return x.LitePcvr
	}
	return 0
}

func (x *CpdAlgParam) GetPctr() float32 {
	if x != nil {
		return x.Pctr
	}
	return 0
}

func (x *CpdAlgParam) GetPcvr() float32 {
	if x != nil {
		return x.Pcvr
	}
	return 0
}

func (x *CpdAlgParam) GetPcvr2() float32 {
	if x != nil {
		return x.Pcvr2
	}
	return 0
}

func (x *CpdAlgParam) GetRerankType() int32 {
	if x != nil {
		return x.RerankType
	}
	return 0
}

var File_protocol_rank2_tagb_proto protoreflect.FileDescriptor

var file_protocol_rank2_tagb_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x32,
	0x2f, 0x74, 0x61, 0x67, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x74, 0x72,
	0x73, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0xec, 0x01, 0x0a, 0x0b, 0x43, 0x70, 0x64, 0x41,
	0x6c, 0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65,
	0x63, 0x61, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x66, 0x74,
	0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0c, 0x73, 0x6f, 0x66, 0x74, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x69, 0x74, 0x65, 0x5f, 0x70, 0x63, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x08, 0x6c, 0x69, 0x74, 0x65, 0x50, 0x63, 0x74, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69,
	0x74, 0x65, 0x5f, 0x70, 0x63, 0x76, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x6c,
	0x69, 0x74, 0x65, 0x50, 0x63, 0x76, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x63, 0x74, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x63, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x63, 0x76, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x63, 0x76, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x63, 0x76, 0x72, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x70, 0x63, 0x76, 0x72, 0x32, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x72, 0x61, 0x6e, 0x6b, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x72, 0x61,
	0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x32, 0x2f, 0x3b, 0x72, 0x61, 0x6e, 0x6b, 0x32, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_rank2_tagb_proto_rawDescOnce sync.Once
	file_protocol_rank2_tagb_proto_rawDescData = file_protocol_rank2_tagb_proto_rawDesc
)

func file_protocol_rank2_tagb_proto_rawDescGZIP() []byte {
	file_protocol_rank2_tagb_proto_rawDescOnce.Do(func() {
		file_protocol_rank2_tagb_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_rank2_tagb_proto_rawDescData)
	})
	return file_protocol_rank2_tagb_proto_rawDescData
}

var file_protocol_rank2_tagb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_rank2_tagb_proto_goTypes = []interface{}{
	(*CpdAlgParam)(nil), // 0: rtrs_frame.CpdAlgParam
}
var file_protocol_rank2_tagb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_rank2_tagb_proto_init() }
func file_protocol_rank2_tagb_proto_init() {
	if File_protocol_rank2_tagb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_rank2_tagb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpdAlgParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_rank2_tagb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_rank2_tagb_proto_goTypes,
		DependencyIndexes: file_protocol_rank2_tagb_proto_depIdxs,
		MessageInfos:      file_protocol_rank2_tagb_proto_msgTypes,
	}.Build()
	File_protocol_rank2_tagb_proto = out.File
	file_protocol_rank2_tagb_proto_rawDesc = nil
	file_protocol_rank2_tagb_proto_goTypes = nil
	file_protocol_rank2_tagb_proto_depIdxs = nil
}
