// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: test_orm.proto

package test_orm

import (
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sex  int32  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_orm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_test_orm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_test_orm_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateStudentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Convention dictates that this field be of the given type, and be
	// named 'payload' in order to autogenerate the handler
	Info *User `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CreateStudentReq) Reset() {
	*x = CreateStudentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_orm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStudentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentReq) ProtoMessage() {}

func (x *CreateStudentReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_orm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentReq.ProtoReflect.Descriptor instead.
func (*CreateStudentReq) Descriptor() ([]byte, []int) {
	return file_test_orm_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStudentReq) GetInfo() *User {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateStudentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Convention also requires that the return type be the same and named 'result'
	Info *User `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CreateStudentRsp) Reset() {
	*x = CreateStudentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_orm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateStudentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentRsp) ProtoMessage() {}

func (x *CreateStudentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_orm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentRsp.ProtoReflect.Descriptor instead.
func (*CreateStudentRsp) Descriptor() ([]byte, []int) {
	return file_test_orm_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentRsp) GetInfo() *User {
	if x != nil {
		return x.Info
	}
	return nil
}

type ReadStudentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// For a read request, the id field is the only to be specified
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadStudentReq) Reset() {
	*x = ReadStudentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_orm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStudentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStudentReq) ProtoMessage() {}

func (x *ReadStudentReq) ProtoReflect() protoreflect.Message {
	mi := &file_test_orm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStudentReq.ProtoReflect.Descriptor instead.
func (*ReadStudentReq) Descriptor() ([]byte, []int) {
	return file_test_orm_proto_rawDescGZIP(), []int{3}
}

func (x *ReadStudentReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReadStudentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Again the type with 'result' name
	Result *User `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReadStudentRsp) Reset() {
	*x = ReadStudentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_orm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadStudentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStudentRsp) ProtoMessage() {}

func (x *ReadStudentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_test_orm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStudentRsp.ProtoReflect.Descriptor instead.
func (*ReadStudentRsp) Descriptor() ([]byte, []int) {
	return file_test_orm_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStudentRsp) GetResult() *User {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_test_orm_proto protoreflect.FileDescriptor

var file_test_orm_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x62, 0x6c, 0x6f, 0x78, 0x6f, 0x70, 0x65, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x72, 0x6d,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x3a, 0x06, 0xba, 0xb9, 0x19, 0x02, 0x08, 0x01, 0x22, 0x36, 0x0a, 0x10, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x22, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x36, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75,
	0x64, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x20, 0x0a, 0x0e, 0x52,
	0x65, 0x61, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x26, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x9b, 0x01, 0x0a, 0x0f, 0x49, 0x6e, 0x74, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3c, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x18, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f,
	0x72, 0x6d, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x18, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x2e, 0x52, 0x65, 0x61,
	0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x1a, 0x06, 0xba,
	0xb9, 0x19, 0x02, 0x08, 0x01, 0x42, 0x1b, 0x5a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x72, 0x6d, 0x3b, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f,
	0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_orm_proto_rawDescOnce sync.Once
	file_test_orm_proto_rawDescData = file_test_orm_proto_rawDesc
)

func file_test_orm_proto_rawDescGZIP() []byte {
	file_test_orm_proto_rawDescOnce.Do(func() {
		file_test_orm_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_orm_proto_rawDescData)
	})
	return file_test_orm_proto_rawDescData
}

var file_test_orm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_orm_proto_goTypes = []interface{}{
	(*User)(nil),             // 0: test_orm.User
	(*CreateStudentReq)(nil), // 1: test_orm.CreateStudentReq
	(*CreateStudentRsp)(nil), // 2: test_orm.CreateStudentRsp
	(*ReadStudentReq)(nil),   // 3: test_orm.ReadStudentReq
	(*ReadStudentRsp)(nil),   // 4: test_orm.ReadStudentRsp
}
var file_test_orm_proto_depIdxs = []int32{
	0, // 0: test_orm.CreateStudentReq.info:type_name -> test_orm.User
	0, // 1: test_orm.CreateStudentRsp.info:type_name -> test_orm.User
	0, // 2: test_orm.ReadStudentRsp.result:type_name -> test_orm.User
	1, // 3: test_orm.IntPointService.Create:input_type -> test_orm.CreateStudentReq
	3, // 4: test_orm.IntPointService.Read:input_type -> test_orm.ReadStudentReq
	2, // 5: test_orm.IntPointService.Create:output_type -> test_orm.CreateStudentRsp
	4, // 6: test_orm.IntPointService.Read:output_type -> test_orm.ReadStudentRsp
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_test_orm_proto_init() }
func file_test_orm_proto_init() {
	if File_test_orm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_orm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_orm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStudentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_orm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateStudentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_orm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStudentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_orm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadStudentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_orm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_orm_proto_goTypes,
		DependencyIndexes: file_test_orm_proto_depIdxs,
		MessageInfos:      file_test_orm_proto_msgTypes,
	}.Build()
	File_test_orm_proto = out.File
	file_test_orm_proto_rawDesc = nil
	file_test_orm_proto_goTypes = nil
	file_test_orm_proto_depIdxs = nil
}
