
proto_library(
    name = 'feature-proto',
    srcs = glob([
            './*.proto',
            './*/*.proto',
            './*/*/*.proto',
            './*/*/*/*.proto',
            './*/*/*/*/*.proto',
            './*/*/*/*/*/*.proto',
        ]),
    deps = [
    ],
)
