// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: protocol/common/flow.proto

package rec5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 流量信息
type FlowInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DebugSwitch         uint32  `protobuf:"varint,1,opt,name=debug_switch,json=debugSwitch,proto3" json:"debug_switch,omitempty"`                             // 0 不需要调试信息， 1打开调试信息
	FlowType            uint32  `protobuf:"varint,2,opt,name=flow_type,json=flowType,proto3" json:"flow_type,omitempty"`                                      // 0 online, 1 passby, 2 test, 3 pressure
	SamplingRate        float64 `protobuf:"fixed64,3,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"`                         // 采样率 0 ~ 1之间
	DebugId             string  `protobuf:"bytes,4,opt,name=debug_id,json=debugId,proto3" json:"debug_id,omitempty"`                                          // 唯一id
	FlowTarget          int32   `protobuf:"varint,5,opt,name=flow_target,json=flowTarget,proto3" json:"flow_target,omitempty"`                                // 0-rank3, 1-头条
	FlowSource          int32   `protobuf:"varint,6,opt,name=flow_source,json=flowSource,proto3" json:"flow_source,omitempty"`                                // 1-vivo, 2-非vivo 标识流量来源，目前只有vivo和非vivo，默认应该为1
	EnterDetailPageType int32   `protobuf:"varint,7,opt,name=enter_detail_page_type,json=enterDetailPageType,proto3" json:"enter_detail_page_type,omitempty"` // 进入详情页场景 0.默认，非push 1-通知栏push 2-应用内push
	PushLevel           int32   `protobuf:"varint,8,opt,name=push_level,json=pushLevel,proto3" json:"push_level,omitempty"`                                   // push等级 1.一级push 2.二级push 3.三级push
}

func (x *FlowInfo) Reset() {
	*x = FlowInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_flow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowInfo) ProtoMessage() {}

func (x *FlowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_flow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowInfo.ProtoReflect.Descriptor instead.
func (*FlowInfo) Descriptor() ([]byte, []int) {
	return file_protocol_common_flow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowInfo) GetDebugSwitch() uint32 {
	if x != nil {
		return x.DebugSwitch
	}
	return 0
}

func (x *FlowInfo) GetFlowType() uint32 {
	if x != nil {
		return x.FlowType
	}
	return 0
}

func (x *FlowInfo) GetSamplingRate() float64 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *FlowInfo) GetDebugId() string {
	if x != nil {
		return x.DebugId
	}
	return ""
}

func (x *FlowInfo) GetFlowTarget() int32 {
	if x != nil {
		return x.FlowTarget
	}
	return 0
}

func (x *FlowInfo) GetFlowSource() int32 {
	if x != nil {
		return x.FlowSource
	}
	return 0
}

func (x *FlowInfo) GetEnterDetailPageType() int32 {
	if x != nil {
		return x.EnterDetailPageType
	}
	return 0
}

func (x *FlowInfo) GetPushLevel() int32 {
	if x != nil {
		return x.PushLevel
	}
	return 0
}

// 模块内条目粒度Debug信息
type DebugItemValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *DebugItemValue) Reset() {
	*x = DebugItemValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_flow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugItemValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugItemValue) ProtoMessage() {}

func (x *DebugItemValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_flow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugItemValue.ProtoReflect.Descriptor instead.
func (*DebugItemValue) Descriptor() ([]byte, []int) {
	return file_protocol_common_flow_proto_rawDescGZIP(), []int{1}
}

func (x *DebugItemValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DebugItemValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 模块粒度Debug信息
type DebugModuleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleName string            `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	ItemValue  []*DebugItemValue `protobuf:"bytes,2,rep,name=item_value,json=itemValue,proto3" json:"item_value,omitempty"`
}

func (x *DebugModuleInfo) Reset() {
	*x = DebugModuleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_flow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugModuleInfo) ProtoMessage() {}

func (x *DebugModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_flow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugModuleInfo.ProtoReflect.Descriptor instead.
func (*DebugModuleInfo) Descriptor() ([]byte, []int) {
	return file_protocol_common_flow_proto_rawDescGZIP(), []int{2}
}

func (x *DebugModuleInfo) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *DebugModuleInfo) GetItemValue() []*DebugItemValue {
	if x != nil {
		return x.ItemValue
	}
	return nil
}

// 服务粒度Debug信息
type DebugServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string             `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ModuleInfo  []*DebugModuleInfo `protobuf:"bytes,2,rep,name=module_info,json=moduleInfo,proto3" json:"module_info,omitempty"`
}

func (x *DebugServiceInfo) Reset() {
	*x = DebugServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_flow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugServiceInfo) ProtoMessage() {}

func (x *DebugServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_flow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugServiceInfo.ProtoReflect.Descriptor instead.
func (*DebugServiceInfo) Descriptor() ([]byte, []int) {
	return file_protocol_common_flow_proto_rawDescGZIP(), []int{3}
}

func (x *DebugServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DebugServiceInfo) GetModuleInfo() []*DebugModuleInfo {
	if x != nil {
		return x.ModuleInfo
	}
	return nil
}

// Debug信息
type DebugInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceInfo []*DebugServiceInfo `protobuf:"bytes,1,rep,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_flow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_flow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_protocol_common_flow_proto_rawDescGZIP(), []int{4}
}

func (x *DebugInfo) GetServiceInfo() []*DebugServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

var File_protocol_common_flow_proto protoreflect.FileDescriptor

var file_protocol_common_flow_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x65,
	0x63, 0x35, 0x22, 0xa0, 0x02, 0x0a, 0x08, 0x46, 0x6c, 0x6f, 0x77, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x64, 0x65, 0x62, 0x75, 0x67, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x69, 0x6e, 0x67,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x62, 0x75, 0x67, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x77, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x33, 0x0a, 0x16, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x13, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x75, 0x73, 0x68,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x38, 0x0a, 0x0e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x49, 0x74,
	0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x67, 0x0a, 0x0f, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x65, 0x63, 0x35, 0x2e, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x69,
	0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6d, 0x0a, 0x10, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x36, 0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x65, 0x63, 0x35, 0x2e, 0x44, 0x65, 0x62, 0x75,
	0x67, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x46, 0x0a, 0x09, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x65, 0x63,
	0x35, 0x2e, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x72, 0x65, 0x63, 0x35, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protocol_common_flow_proto_rawDescOnce sync.Once
	file_protocol_common_flow_proto_rawDescData = file_protocol_common_flow_proto_rawDesc
)

func file_protocol_common_flow_proto_rawDescGZIP() []byte {
	file_protocol_common_flow_proto_rawDescOnce.Do(func() {
		file_protocol_common_flow_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_common_flow_proto_rawDescData)
	})
	return file_protocol_common_flow_proto_rawDescData
}

var file_protocol_common_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protocol_common_flow_proto_goTypes = []interface{}{
	(*FlowInfo)(nil),         // 0: rec5.FlowInfo
	(*DebugItemValue)(nil),   // 1: rec5.DebugItemValue
	(*DebugModuleInfo)(nil),  // 2: rec5.DebugModuleInfo
	(*DebugServiceInfo)(nil), // 3: rec5.DebugServiceInfo
	(*DebugInfo)(nil),        // 4: rec5.DebugInfo
}
var file_protocol_common_flow_proto_depIdxs = []int32{
	1, // 0: rec5.DebugModuleInfo.item_value:type_name -> rec5.DebugItemValue
	2, // 1: rec5.DebugServiceInfo.module_info:type_name -> rec5.DebugModuleInfo
	3, // 2: rec5.DebugInfo.service_info:type_name -> rec5.DebugServiceInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protocol_common_flow_proto_init() }
func file_protocol_common_flow_proto_init() {
	if File_protocol_common_flow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_common_flow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FlowInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_flow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugItemValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_flow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugModuleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_flow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_flow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DebugInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_common_flow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_flow_proto_goTypes,
		DependencyIndexes: file_protocol_common_flow_proto_depIdxs,
		MessageInfos:      file_protocol_common_flow_proto_msgTypes,
	}.Build()
	File_protocol_common_flow_proto = out.File
	file_protocol_common_flow_proto_rawDesc = nil
	file_protocol_common_flow_proto_goTypes = nil
	file_protocol_common_flow_proto_depIdxs = nil
}
