// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: protocol/common/uac.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Uac接口响应
type MixItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mixia   float32 `protobuf:"fixed32,1,opt,name=mixia,proto3" json:"mixia,omitempty"`   //新增广告内部排序超参
	Mixib   float32 `protobuf:"fixed32,2,opt,name=mixib,proto3" json:"mixib,omitempty"`   //新增广告内部排序超参
	Mixoext string  `protobuf:"bytes,3,opt,name=mixoext,proto3" json:"mixoext,omitempty"` //新增预留自然和广告融合超参
}

func (x *MixItem) Reset() {
	*x = MixItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_uac_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MixItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixItem) ProtoMessage() {}

func (x *MixItem) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_uac_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixItem.ProtoReflect.Descriptor instead.
func (*MixItem) Descriptor() ([]byte, []int) {
	return file_protocol_common_uac_proto_rawDescGZIP(), []int{0}
}

func (x *MixItem) GetMixia() float32 {
	if x != nil {
		return x.Mixia
	}
	return 0
}

func (x *MixItem) GetMixib() float32 {
	if x != nil {
		return x.Mixib
	}
	return 0
}

func (x *MixItem) GetMixoext() string {
	if x != nil {
		return x.Mixoext
	}
	return ""
}

type ResponseValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ii    int32    `protobuf:"varint,1,opt,name=ii,proto3" json:"ii,omitempty"`
	Cts   []int32  `protobuf:"varint,2,rep,packed,name=cts,proto3" json:"cts,omitempty"`
	Cvs   []int32  `protobuf:"varint,3,rep,packed,name=cvs,proto3" json:"cvs,omitempty"`
	Cvs2  []int32  `protobuf:"varint,4,rep,packed,name=cvs2,proto3" json:"cvs2,omitempty"`
	I     int32    `protobuf:"varint,5,opt,name=i,proto3" json:"i,omitempty"`         //appid
	Pw    int32    `protobuf:"varint,6,opt,name=pw,proto3" json:"pw,omitempty"`       //payWill
	Ltv   int64    `protobuf:"varint,7,opt,name=ltv,proto3" json:"ltv,omitempty"`     //统计ltv
	Score int64    `protobuf:"varint,8,opt,name=score,proto3" json:"score,omitempty"` //游戏打分score
	TagA  string   `protobuf:"bytes,9,opt,name=tagA,proto3" json:"tagA,omitempty"`
	TagB  string   `protobuf:"bytes,10,opt,name=tagB,proto3" json:"tagB,omitempty"`
	Item  *MixItem `protobuf:"bytes,11,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *ResponseValue) Reset() {
	*x = ResponseValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_uac_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseValue) ProtoMessage() {}

func (x *ResponseValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_uac_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseValue.ProtoReflect.Descriptor instead.
func (*ResponseValue) Descriptor() ([]byte, []int) {
	return file_protocol_common_uac_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseValue) GetIi() int32 {
	if x != nil {
		return x.Ii
	}
	return 0
}

func (x *ResponseValue) GetCts() []int32 {
	if x != nil {
		return x.Cts
	}
	return nil
}

func (x *ResponseValue) GetCvs() []int32 {
	if x != nil {
		return x.Cvs
	}
	return nil
}

func (x *ResponseValue) GetCvs2() []int32 {
	if x != nil {
		return x.Cvs2
	}
	return nil
}

func (x *ResponseValue) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *ResponseValue) GetPw() int32 {
	if x != nil {
		return x.Pw
	}
	return 0
}

func (x *ResponseValue) GetLtv() int64 {
	if x != nil {
		return x.Ltv
	}
	return 0
}

func (x *ResponseValue) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ResponseValue) GetTagA() string {
	if x != nil {
		return x.TagA
	}
	return ""
}

func (x *ResponseValue) GetTagB() string {
	if x != nil {
		return x.TagB
	}
	return ""
}

func (x *ResponseValue) GetItem() *MixItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type TouTiaoMultipleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Value    []*ResponseValue `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	Version  string           `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Adxvalue []*ResponseValue `protobuf:"bytes,4,rep,name=adxvalue,proto3" json:"adxvalue,omitempty"`
}

func (x *TouTiaoMultipleResponse) Reset() {
	*x = TouTiaoMultipleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_uac_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TouTiaoMultipleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouTiaoMultipleResponse) ProtoMessage() {}

func (x *TouTiaoMultipleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_uac_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouTiaoMultipleResponse.ProtoReflect.Descriptor instead.
func (*TouTiaoMultipleResponse) Descriptor() ([]byte, []int) {
	return file_protocol_common_uac_proto_rawDescGZIP(), []int{2}
}

func (x *TouTiaoMultipleResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TouTiaoMultipleResponse) GetValue() []*ResponseValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TouTiaoMultipleResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TouTiaoMultipleResponse) GetAdxvalue() []*ResponseValue {
	if x != nil {
		return x.Adxvalue
	}
	return nil
}

var File_protocol_common_uac_proto protoreflect.FileDescriptor

var file_protocol_common_uac_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x75, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x07, 0x4d, 0x69, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x69, 0x78, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x6d,
	0x69, 0x78, 0x69, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x69, 0x78, 0x69, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x6d, 0x69, 0x78, 0x69, 0x62, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x69,
	0x78, 0x6f, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x69, 0x78,
	0x6f, 0x65, 0x78, 0x74, 0x22, 0xea, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x03, 0x63, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x63, 0x76, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x76,
	0x73, 0x32, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x63, 0x76, 0x73, 0x32, 0x12, 0x0c,
	0x0a, 0x01, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x0e, 0x0a, 0x02,
	0x70, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x70, 0x77, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x74, 0x76, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6c, 0x74, 0x76, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x41, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x41, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x42,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x42, 0x12, 0x23, 0x0a, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x69, 0x78, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0xa7, 0x01, 0x0a, 0x17, 0x54, 0x6f, 0x75, 0x54, 0x69, 0x61, 0x6f, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x08, 0x61, 0x64, 0x78, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x08, 0x61, 0x64, 0x78, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x28, 0x5a, 0x26, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x3b, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_common_uac_proto_rawDescOnce sync.Once
	file_protocol_common_uac_proto_rawDescData = file_protocol_common_uac_proto_rawDesc
)

func file_protocol_common_uac_proto_rawDescGZIP() []byte {
	file_protocol_common_uac_proto_rawDescOnce.Do(func() {
		file_protocol_common_uac_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_common_uac_proto_rawDescData)
	})
	return file_protocol_common_uac_proto_rawDescData
}

var file_protocol_common_uac_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocol_common_uac_proto_goTypes = []interface{}{
	(*MixItem)(nil),                 // 0: common.MixItem
	(*ResponseValue)(nil),           // 1: common.ResponseValue
	(*TouTiaoMultipleResponse)(nil), // 2: common.TouTiaoMultipleResponse
}
var file_protocol_common_uac_proto_depIdxs = []int32{
	0, // 0: common.ResponseValue.item:type_name -> common.MixItem
	1, // 1: common.TouTiaoMultipleResponse.value:type_name -> common.ResponseValue
	1, // 2: common.TouTiaoMultipleResponse.adxvalue:type_name -> common.ResponseValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protocol_common_uac_proto_init() }
func file_protocol_common_uac_proto_init() {
	if File_protocol_common_uac_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_common_uac_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MixItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_uac_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_uac_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TouTiaoMultipleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_common_uac_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_uac_proto_goTypes,
		DependencyIndexes: file_protocol_common_uac_proto_depIdxs,
		MessageInfos:      file_protocol_common_uac_proto_msgTypes,
	}.Build()
	File_protocol_common_uac_proto = out.File
	file_protocol_common_uac_proto_rawDesc = nil
	file_protocol_common_uac_proto_goTypes = nil
	file_protocol_common_uac_proto_depIdxs = nil
}
