// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: protocol/abt/abt_service.proto

package rec5

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protocol_abt_abt_service_proto protoreflect.FileDescriptor

var file_protocol_abt_abt_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x61, 0x62, 0x74, 0x2f, 0x61,
	0x62, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x72, 0x65, 0x63, 0x35, 0x1a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x61, 0x62, 0x74, 0x2f, 0x72, 0x74, 0x72, 0x73, 0x5f, 0x61, 0x62, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x39, 0x0a, 0x0a, 0x41, 0x62, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x0f, 0x2e,
	0x72, 0x65, 0x63, 0x35, 0x2e, 0x41, 0x62, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x72, 0x65, 0x63, 0x35, 0x2e, 0x41, 0x62, 0x74, 0x65, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x72, 0x65, 0x63, 0x35, 0x80, 0x01, 0x01, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_protocol_abt_abt_service_proto_goTypes = []interface{}{
	(*AbtestReq)(nil), // 0: rec5.AbtestReq
	(*AbtestRsp)(nil), // 1: rec5.AbtestRsp
}
var file_protocol_abt_abt_service_proto_depIdxs = []int32{
	0, // 0: rec5.AbtService.route:input_type -> rec5.AbtestReq
	1, // 1: rec5.AbtService.route:output_type -> rec5.AbtestRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_abt_abt_service_proto_init() }
func file_protocol_abt_abt_service_proto_init() {
	if File_protocol_abt_abt_service_proto != nil {
		return
	}
	file_protocol_abt_rtrs_abtest_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_abt_abt_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_abt_abt_service_proto_goTypes,
		DependencyIndexes: file_protocol_abt_abt_service_proto_depIdxs,
	}.Build()
	File_protocol_abt_abt_service_proto = out.File
	file_protocol_abt_abt_service_proto_rawDesc = nil
	file_protocol_abt_abt_service_proto_goTypes = nil
	file_protocol_abt_abt_service_proto_depIdxs = nil
}
